import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    paddingTop: 50,
  },
  headerTitle: {
    fontSize: 24,
    color: '#FFFFFF',
    fontFamily: 'Montserrat',
    fontWeight: '600',
  },
  profileButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#1DB954',
    borderRadius: 22,
  },
  profileIcon: {
    width: 24,
    height: 24,
    tintColor: '#1DB954',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 120, // Espaço para bottom tab
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingVertical: 20,
  },
  sectionTitle: {
    fontSize: 20,
    color: '#FFFFFF',
    fontFamily: 'Montserrat',
    fontWeight: '600',
    marginBottom: 20,
    marginTop: 10,
  },
  // Emergency contact item
  contactItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginBottom: 12,
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    fontSize: 18,
    color: '#FFFFFF',
    fontFamily: 'Montserrat',
    fontWeight: '500',
  },
  contactPhone: {
    fontSize: 14,
    color: '#CCCCCC',
    fontFamily: 'Montserrat',
    fontWeight: '400',
    marginTop: 4,
  },
  contactRelationship: {
    fontSize: 12,
    color: '#1DB954',
    fontFamily: 'Montserrat',
    fontWeight: '400',
    marginTop: 2,
  },
  phoneButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1DB954',
    borderRadius: 20,
    marginLeft: 10,
  },
  phoneIcon: {
    width: 20,
    height: 20,
    tintColor: '#000000',
  },
  // Personal contacts section
  personalContactsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 20,
  },
  addContactButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1DB954',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
  addContactText: {
    fontSize: 14,
    color: '#000000',
    fontFamily: 'Montserrat',
    fontWeight: '600',
    marginRight: 5,
  },
  addIcon: {
    fontSize: 16,
    color: '#000000',
    fontWeight: 'bold',
  },
  personalContactItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginBottom: 12,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#1DB954',
    borderRadius: 10,
  },
  personalContactActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButton: {
    marginLeft: 10,
  },
  editIcon: {
    width: 18,
    height: 18,
    tintColor: '#1DB954',
  },
  deleteIcon: {
    width: 18,
    height: 18,
    tintColor: '#FF4444',
  },
  primaryBadge: {
    backgroundColor: '#FFD700',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginTop: 4,
  },
  primaryText: {
    fontSize: 10,
    color: '#000000',
    fontFamily: 'Montserrat',
    fontWeight: '600',
  },
  emptyPersonalContacts: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyText: {
    fontSize: 16,
    color: '#CCCCCC',
    fontFamily: 'Montserrat',
    fontWeight: '400',
    textAlign: 'center',
    lineHeight: 24,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#1a1a1a',
    borderWidth: 2,
    borderColor: '#1DB954',
    borderRadius: 12,
    padding: 20,
    width: width - 40,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 18,
    color: '#FFFFFF',
    fontFamily: 'Montserrat',
    fontWeight: '600',
    marginBottom: 20,
  },
  formContainer: {
    marginBottom: 20,
  },
  inputGroup: {
    marginBottom: 15,
  },
  inputLabel: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'Montserrat',
    fontWeight: '500',
    marginBottom: 8,
  },
  input: {
    height: 45,
    backgroundColor: '#333333',
    borderWidth: 1,
    borderColor: '#1DB954',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#FFFFFF',
    fontFamily: 'Montserrat',
  },
  inputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inputHalf: {
    width: '48%',
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  switchLabel: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'Montserrat',
    fontWeight: '500',
  },
  switch: {
    width: 50,
    height: 25,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#1DB954',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  switchActive: {
    backgroundColor: '#1DB954',
  },
  switchInactive: {
    backgroundColor: 'transparent',
  },
  switchThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cancelButton: {
    flex: 1,
    height: 45,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#1DB954',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  cancelButtonText: {
    fontSize: 16,
    color: '#1DB954',
    fontFamily: 'Montserrat',
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    height: 45,
    backgroundColor: '#1DB954',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  saveButtonText: {
    fontSize: 16,
    color: '#000000',
    fontFamily: 'Montserrat',
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontFamily: 'Montserrat',
    fontWeight: '500',
    marginTop: 20,
  },
});

export default styles;